clone_folder: c:\go\src\github.com\github\git-lfs

environment:
  GOPATH: c:\go
  GOVERSION: 1.7

install:
  - set PATH=%GOPATH%\bin;%PATH%;
  # - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  # - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - cinst InnoSetup -y
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%;

test_script:
  - bash -c 'script/cibuild'

build_script:
  - bash -c 'GOARCH=386 script/bootstrap'
  - mv bin\git-lfs git-lfs-x86.exe
  - bash -c 'GOARCH=amd64 script/bootstrap'
  - mv bin\git-lfs git-lfs-x64.exe

after_build:
  - iscc script\windows-installer\inno-setup-git-lfs-installer.iss

artifacts:
  - path: git-lfs-x86.exe
  - path: git-lfs-x64.exe
  - path: git-lfs-windows-*.exe
